In [2]:
[1, 2] == [0, 2]

False

In [6]:
np.array([1, 2]) + [0, 2]

array([1, 4])

In [9]:
- np.array([1, 2])

array([-1, -2])

In [12]:
np.array([1, 2]) == np.array([1, 2])

array([ True,  True])

In [15]:
np.array([1, 2]) * np.array([1, 2])

array([1, 4])

In [19]:
np.matrix([1, 1]) * np.matrix([1, 2]).reshape((2, 1))

matrix([[3]])

In [19]:
np.zeros(np.matrix([1, 1]).T.shape)

array([[0.],
       [0.]])

In [21]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [1]:
import numpy as np
import math

In [21]:
def Jacobian(x : list):
    return [[x[1] ** 3 - 7, 3 * (x[0] + 3) * (x[1] ** 2)], 
            [math.cos(x[1] * math.exp(x[0]) - 1) * x[1] * math.exp(x[0]), 
            math.cos(x[1] * math.exp(x[0]) - 1) * math.exp(x[0])]]
    
Jacobian([-0.5, 1.4])

[[-4.256, 14.699999999999998], [0.83949889738304, 0.5996420695593143]]

In [15]:
def NewtonMethod():
    def Jacobian(x : list):
        return [[x[1] ** 3 - 7, 3 * (x[0] + 3) * (x[1] ** 2)], 
                [math.cos(x[1] * math.exp(x[0]) - 1) * x[1] * math.exp(x[0]), 
                math.cos(x[1] * math.exp(x[0]) - 1) * math.exp(x[0])]]
    
    def f(x : list):
        return np.array([(x[0] + 3) * (x[1] ** 3  - 7) + 18, math.sin(x[1] * math.exp(x[0]) - 1)])
    
    
    x1 = np.array([-0.5, 1.4])
    x0 = np.array([0, 0])
    while(not (f(x1) == [0, 0]).all()):
        x0 = x1
        sol = np.linalg.solve(Jacobian(x0), -f(x0))
        x1 = x0 + sol
        print("Error: ", x1 - [0, 1])
    

NewtonMethod()
        
        

Error:  [-0.05531514  0.02806658]
Error:  [-0.00014035  0.0001574 ]
Error:  [-1.77907770e-08  5.55138535e-09]
Error:  [1.18056312e-16 0.00000000e+00]
Error:  [-1.51704507e-17 -1.11022302e-16]
Error:  [ 5.14429307e-17 -1.11022302e-16]
Error:  [ 1.18056312e-16 -1.11022302e-16]


In [16]:
def BroydenMethod(): 
    def f(x : list):
        return np.array([(x[0] + 3) * (x[1] ** 3  - 7) + 18, math.sin(x[1] * math.exp(x[0]) - 1)])
    
    B0 = np.matrix([[-4.256, 14.699999999999998], [0.83949889738304, 0.5996420695593143]])
    x1 = np.array([-0.5, 1.4])
    x0 = np.array([0, 0])
    while(not (f(x1) == [0, 0]).all()):
        x0 = x1
        sol = np.linalg.solve(B0, -f(x0))
        x1 = x0 + sol
        yk = np.matrix(f(x1) -  f(x0)).reshape((2, 1))
        denominator = (yk - B0 * np.matrix(sol).reshape((2, 1))) * np.matrix(sol).reshape((1, 2))
        B0 = B0 + denominator/sum(sol * sol)
        print("Error: ", x1 - [0, 1])

BroydenMethod()

Error:  [-0.05531514  0.02806658]
Error:  [0.00050995 0.00012364]
Error:  [-2.33847864e-04  7.65608693e-05]
Error:  [-4.08262210e-05  1.35978908e-05]
Error:  [-1.32750896e-07  4.53383611e-08]
Error:  [-5.39120623e-10  1.80663262e-10]
Error:  [ 1.66791236e-12 -5.57109914e-13]
Error:  [-1.08051128e-15  4.44089210e-16]
Error:  [-5.52378292e-18  0.00000000e+00]


In [7]:
def NewtonMethod(x1):
    def Jacobian(x : list):
        return [[0, 0, 1, 1], 
                [x[2], x[3], x[0], x[1]],
                [2 * x[2] * x[0], 2 * x[3] * x[1], x[0] ** 2, x[1] ** 2],
                [3 * x[2] * x[0] ** 2, 3 * x[3] * x[1] ** 2 , x[0] ** 3, x[1] ** 3 ]]
    
    def f(x : list):
        return np.array([x[2] + x[3]- 2,
                        x[2] * x[0] + x[3] * x[1],
                        x[2] * (x[0] ** 2) + x[3] * (x[1] ** 2) - 2.0/3,
                        x[2] * (x[0] ** 3) + x[3] * (x[1] ** 3)])
    
    x0 = np.array([float('inf'), 0, 0, 0])
    inum = 0
    while(inum <= 50 and not (x1 == x0).all()):
        inum += 1
        x0 = x1
        sol = np.linalg.solve(Jacobian(x0), -f(x0))
        x1 = x0 + sol
    return x1

NewtonMethod([-2, 1, 3, -1])

array([-0.57735027,  0.57735027,  1.        ,  1.        ])

In [6]:
NewtonMethod([-5, -4, -5, -4])

array([-0.57735027,  0.57735027,  1.        ,  1.        ])

In [ ]:
def f(x : list):
    return np.array([x[2] + x[3]- 2,
                    x[2] * x[0] + x[3] * x[1],
                    x[2] * (x[0] ** 2) + x[3] * (x[1] ** 2) - 2.0/3,
                    x[2] * (x[0] ** 3) + x[3] * (x[1] ** 3)])
solSet = set()
for x1 in range(-10, 10):
    for x2 in range(-10, 10):
        for w1 in range(-10, 10):
            for w2 in range(-10, 10):
                try:
                    sol = NewtonMethod([x1,x2,w1,w2])
                    if str(sol) not in solSet:
                        solSet.add(str(sol))
                        if max(np.abs(f(sol))) < 0.001:
                            print([x1,x2,w1,w2], ": ", sol, " ", f(sol))
                except:
                    pass

In [ ]:
import numpy as np

def experiment(epsilon):
    M = [[1.0, 1.0+epsilon],
        [1.0-epsilon, 1.0]]
    
    b = [1.0+(1.0+epsilon)*epsilon, 1.0]
    
    db = [epsilon * epsilon, 0]
    cond = np.linalg.cond(M, p=1)
    sol = np.linalg.solve(M, b)
    
    print("Experimental Epsilon: ", epsilon ** 2)
    print("Condtion Number: ", cond)
    print("Error Bounds: ", cond * np.linalg.norm(db, ord=1) / np.linalg.norm(M, ord=1))
    print("Relative Error for Each Components: ", [sol[0] - 1, sol[1]/epsilon - 1 ])
    print("Relative Error 2 Norm: ", np.linalg.norm(sol-[1, epsilon], ord=1) / np.linalg.norm([1, epsilon], ord=1))
    print("Solution is: ", sol)


In [13]:
def inverse(A : np.matrix):
    A1 = A.T / (np.linalg.norm(A, ord = 1) * np.linalg.norm(A, ord = np.inf))
    A0 = np.zeros(A.shape)
    I = np.identity(A.shape[0])
    inum = 0
    while (inum <= 50 and not np.max(np.abs((A1 - A0))) < 1e-10):
        inum += 1
        A0 = A1
        A1 = A0 + A0 * (I - A * A0)
        print("Iteration {}: ".format(inum), np.max(np.abs((A1 - A0))))
    
    return A1


A = np.matrix([[1, 2, 3, 4], [3, 4, 5, 6], [7, 8, 9, 10], [11, 12, 13, 14]])
inverse(A)

Iteration 1:  0.0030380622837370246
Iteration 2:  0.0020129586571042014
Iteration 3:  0.002661291479174702
Iteration 4:  0.005330459229441489
Iteration 5:  0.010325699176414587
Iteration 6:  0.01936704424126874
Iteration 7:  0.03408170603682596
Iteration 8:  0.052869732298736566
Iteration 9:  0.06408073280728241
Iteration 10:  0.04843238573234504
Iteration 11:  0.015346610324523613
Iteration 12:  0.0010443710512427762
Iteration 13:  4.290037178333872e-06
Iteration 14:  7.180178673849014e-11


matrix([[-0.25423729, -0.17457627, -0.01525424,  0.1440678 ],
        [-0.09745763, -0.06525424, -0.00084746,  0.06355932],
        [ 0.05932203,  0.0440678 ,  0.01355932, -0.01694915],
        [ 0.21610169,  0.15338983,  0.0279661 , -0.09745763]])

In [67]:
def f(x):
    return x ** 0.5 - 1

def n(x0, x1):
    return (x0 - x1) * f(x1) / (f(x1) - f(x0))

n(1.2, 1.000000000000001)
1.00000000000001 + n(1.2, 1.00000000000001)
n(1.000000000000004, 1.00000000000001) + 1.00000000000001
n(1.00000000000001, 0.9999999999999999) + 0.9999999999999999
n(0.9999999999999999, 1.0000000000000002) + 1.0000000000000002

1.0000000000000002

In [70]:
def f(x):
    return x ** 0.5 - 1

def n(x0, x1):
    return (x0 * f(x1) - x1*f(x0) )/ (f(x1) - f(x0))
            
n(1.2, 1.000000000000001)
n(1.000000000000001, 1.0000000000000002)

1.0000000000000002

In [101]:
2.0 ** 1023

8.98846567431158e+307

In [106]:
2.0 ** 1023 + 2.0 ** 1023

inf

In [110]:


def f(x):
    return x * (2.0 ** (-1023.5)) - 0.5

def n(x0, x1):
    return (x0 * f(x1) - x1*f(x0) )/ (f(x1) - f(x0))
            
n(2.0 ** 1023, -2.0 ** 1023)
n(-2.0 ** 1023, 6.355805030768232e+307)
# n(1.000000000000001, 1.0000000000000002)

6.355805030768232e+307